In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np 


In [2]:
#2. Print the NUMPY version and the configuration.
print(np.version.version) 

1.16.2


In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5)) 

In [6]:
#4. Print a.
print(a) 

[[[0.66665175 0.80496886 0.02536369 0.46902968 0.14398135]
  [0.89648235 0.14928782 0.27268231 0.59742908 0.62306846]
  [0.39834493 0.59374232 0.86180449 0.86768619 0.22619065]]

 [[0.68469519 0.5559137  0.83716549 0.27645783 0.91802835]
  [0.86513575 0.24972244 0.6913091  0.58039516 0.25075115]
  [0.66027183 0.04999159 0.23378627 0.67007101 0.50951032]]]


In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.zeros((5,2,3))+1

In [11]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#7. Do a and b have the same size? How do you prove that in Python code?
''' They do not, you can reshape them '''


In [ ]:
#8. Are you able to add a and b? Why or why not?
'''Yes you can, by reshaping them '''


In [24]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
# Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
print(c) 


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [25]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = (a+c)
print(d)

'''It is working now because they have the same matix format now'''


[[[1.66665175 1.80496886 1.02536369 1.46902968 1.14398135]
  [1.89648235 1.14928782 1.27268231 1.59742908 1.62306846]
  [1.39834493 1.59374232 1.86180449 1.86768619 1.22619065]]

 [[1.68469519 1.5559137  1.83716549 1.27645783 1.91802835]
  [1.86513575 1.24972244 1.6913091  1.58039516 1.25075115]
  [1.66027183 1.04999159 1.23378627 1.67007101 1.50951032]]]


In [26]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

'''The difference is that all elements in d are the elements in a + 1.
This is logic because in matrix b/c there where only elements with the number 1'''


[[[0.66665175 0.80496886 0.02536369 0.46902968 0.14398135]
  [0.89648235 0.14928782 0.27268231 0.59742908 0.62306846]
  [0.39834493 0.59374232 0.86180449 0.86768619 0.22619065]]

 [[0.68469519 0.5559137  0.83716549 0.27645783 0.91802835]
  [0.86513575 0.24972244 0.6913091  0.58039516 0.25075115]
  [0.66027183 0.04999159 0.23378627 0.67007101 0.50951032]]]
[[[1.66665175 1.80496886 1.02536369 1.46902968 1.14398135]
  [1.89648235 1.14928782 1.27268231 1.59742908 1.62306846]
  [1.39834493 1.59374232 1.86180449 1.86768619 1.22619065]]

 [[1.68469519 1.5559137  1.83716549 1.27645783 1.91802835]
  [1.86513575 1.24972244 1.6913091  1.58039516 1.25075115]
  [1.66027183 1.04999159 1.23378627 1.67007101 1.50951032]]]


In [27]:
#12. Multiply a and c. Assign the result to e.
e = (a*c)
print(e)


[[[0.66665175 0.80496886 0.02536369 0.46902968 0.14398135]
  [0.89648235 0.14928782 0.27268231 0.59742908 0.62306846]
  [0.39834493 0.59374232 0.86180449 0.86768619 0.22619065]]

 [[0.68469519 0.5559137  0.83716549 0.27645783 0.91802835]
  [0.86513575 0.24972244 0.6913091  0.58039516 0.25075115]
  [0.66027183 0.04999159 0.23378627 0.67007101 0.50951032]]]


In [28]:
#13. Does e equal to a? Why or why not?
print(e == a) 

'''They are the same because you are multipying with 1'''


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [30]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d) 

print(d_max)
print(d_min) 
print(d_mean)


1.918028350484863
1.025363693281284
1.5209973031202197


In [63]:
#15. Now we want to label the values in d. 
# First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5)) 


In [70]:
'''
#16. Populate the values in f. 
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
'''

# loop trought all the indexes in the array 
    # make 3 for loop: 1 for the amount, one for the rows, one for the colomns 
        # loop trought the rows [0:3]
        # loop trought the colomns [0:5] 
        
'''
for value in f[:,:,:]: 
    if value > d_min and value < d_mean:
        f.fill(25)
    elif value > d_mean and < d_max: 
        f.fill(75)
    elif value == d_mean:
        f.fill(50)
    elif value == d_min:
        f.fill(0)
    elif value == d_max:
        f.fill(100)
'''


'\nfor value in f[:,:,:]: \n    if value > d_min and value < d_mean:\n        f.fill(25)\n    elif value > d_mean and < d_max: \n        f.fill(75)\n    elif value == d_mean:\n        f.fill(50)\n    elif value == d_min:\n        f.fill(0)\n    elif value == d_max:\n        f.fill(100)\n'

In [ ]:
'''
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
